version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: express-app
    restart: always
    # env_file: 
    #   - .env
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_HOST: mysql
      NODE_ENV: development # Bisa diubah ke staging atau production sesuai kebutuhan
      HOST: 0.0.0.0
      PORT: 5000
      URLAPP: https://your-production-url.com
      STAGING_URL: https://your-staging-url.com
    ports:
      - "5000:5000"
    # depends_on:
    #   - mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
